version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: bcal_postgres_prod
    environment:
      POSTGRES_DB: bcal_db
      POSTGRES_USER: bcal_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bcal_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bcal_network
    restart: unless-stopped

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bcal_backend_prod
    environment:
      - DATABASE_URL=postgresql://bcal_user:${POSTGRES_PASSWORD:-bcal_password}@postgres:5432/bcal_db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DEBUG=false
    depends_on:
      - postgres
    networks:
      - bcal_network
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4

  # React Frontend (Built)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: bcal_frontend_prod
    environment:
      - REACT_APP_API_URL=/api
    networks:
      - bcal_network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: bcal_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - bcal_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  bcal_network:
    driver: bridge
