[build]
  # Build command for the React frontend
  command = "cd frontend && npm ci && npm run build"
  
  # Directory to publish (React build output)
  publish = "frontend/build"
  
  # Node.js version
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Environment variables for build
  REACT_APP_API_URL = "https://your-backend-api.railway.app/api"
  REACT_APP_STRIPE_PUBLISHABLE_KEY = "pk_test_your_stripe_publishable_key"
  REACT_APP_ENABLE_MULTI_TENANCY = "true"
  REACT_APP_LICENSING_URL = "https://your-licensing-server.railway.app"

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy to backend (optional - for development)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-api.railway.app/api/:splat"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.stripe.com https://*.railway.app; frame-src https://js.stripe.com https://hooks.stripe.com;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Tenant routing - redirect subdomains
[[redirects]]
  from = "https://:tenant.your-domain.com/*"
  to = "https://your-domain.com/:splat?tenant=:tenant"
  status = 200
  force = true
