"""Add team management, audit logging, and system settings

Revision ID: 19b83ba060c4
Revises: a797fdadb887
Create Date: 2025-08-15 09:49:09.910322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b83ba060c4'
down_revision = 'a797fdadb887'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
