"""add_role_system_and_remove_is_admin

Revision ID: 92095bab6d03
Revises: 19b83ba060c4
Create Date: 2025-08-15 12:06:52.809525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92095bab6d03'
down_revision = '19b83ba060c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
