"""Add SSO and enhanced user fields

Revision ID: c4940ed0d973
Revises: 
Create Date: 2025-08-15 08:36:06.218658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4940ed0d973'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availabilities', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('availabilities', sa.Column('recurring_pattern', sa.String(), nullable=True))
    op.add_column('availabilities', sa.Column('recurring_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('availabilities', sa.Column('recurring_days', sa.JSON(), nullable=True))
    op.add_column('availabilities', sa.Column('buffer_before_minutes', sa.Integer(), nullable=True))
    op.add_column('availabilities', sa.Column('buffer_after_minutes', sa.Integer(), nullable=True))
    op.add_column('availabilities', sa.Column('min_notice_hours', sa.Integer(), nullable=True))
    op.add_column('availabilities', sa.Column('max_booking_days', sa.Integer(), nullable=True))
    op.add_column('availabilities', sa.Column('slot_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('availabilities', sa.Column('sync_with_calendar', sa.Boolean(), nullable=True))
    op.add_column('availabilities', sa.Column('calendar_id', sa.String(), nullable=True))
    op.add_column('availabilities', sa.Column('meeting_type', sa.String(), nullable=True))
    op.add_column('availabilities', sa.Column('meeting_description', sa.Text(), nullable=True))
    op.add_column('availabilities', sa.Column('meeting_location', sa.String(), nullable=True))
    op.add_column('availabilities', sa.Column('meeting_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('auth0_user_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('sso_user_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('sms_notifications', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('reminder_preferences', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['auth0_user_id'])
    op.create_unique_constraint(None, 'users', ['sso_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'reminder_preferences')
    op.drop_column('users', 'sms_notifications')
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'website')
    op.drop_column('users', 'position')
    op.drop_column('users', 'company')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'sso_user_id')
    op.drop_column('users', 'auth0_user_id')
    op.drop_column('availabilities', 'meeting_url')
    op.drop_column('availabilities', 'meeting_location')
    op.drop_column('availabilities', 'meeting_description')
    op.drop_column('availabilities', 'meeting_type')
    op.drop_column('availabilities', 'calendar_id')
    op.drop_column('availabilities', 'sync_with_calendar')
    op.drop_column('availabilities', 'slot_duration_minutes')
    op.drop_column('availabilities', 'max_booking_days')
    op.drop_column('availabilities', 'min_notice_hours')
    op.drop_column('availabilities', 'buffer_after_minutes')
    op.drop_column('availabilities', 'buffer_before_minutes')
    op.drop_column('availabilities', 'recurring_days')
    op.drop_column('availabilities', 'recurring_end_date')
    op.drop_column('availabilities', 'recurring_pattern')
    op.drop_column('availabilities', 'is_recurring')
    # ### end Alembic commands ###
